name: Invalidate Fly Token
on:
  push:
    branches:
      - 'temp-invalidate-token'

jobs:
  cleanup-review-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl auth whoami
          flyctl auth logout
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
